---
- name: Deploy Django Application
  hosts: webserver
  # become: yes
  
  vars:
    app_image: daihuu103/django-hello-world:latest
    app_port: 8000
  
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ app_image }}"
        state: present
        source: pull
    
    - name: Stop existing container
      docker_container:
        name: django-app
        state: absent
        force_kill: yes
      ignore_errors: yes
    
    - name: Run Django container
      docker_container:
        name: django-app
        image: "{{ app_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:8000"
